### ISSUE TITLE
no rRNA sequences were detected in an almost complete genome

### ISSUE THREAD

**Issue by ThomasYJK555** [hzi-bifo/RiboDetector#11]
Hi,
I am with great doubt with the accuracy of "RiboDetector" as a new user since I made a test for my metagenomic-assembly -genomes (MAGs). Several MAG from my previous binning and dRep work with the completeness of >95 and contaminant of <5 were selected for the rRNA detection test in "RiboDetector", the scripts are as follow (taking "MAG2809_RMAG1998.fa" as an example):
ribodetector_cpu -t 20 -l 150 -i /data2/yjk/Bison_meta/rRNA/bin_for_test/MAG2809_RMAG1998.fa -r /data2/yjk/Bison_meta/rRNA/bin_for_test/rRNA/MAG2809_RMAG1998_rRNA.fa -e both -o /data2/yjk/Bison_meta/rRNA/bin_for_test/nonrRNA/MAG2809_RMAG1998_nonrRNA.fa 1>/data2/yjk/Bison_meta/rRNA/bin_for_test/MAG2809_RMAG1998.o 2>/data2/yjk/Bison_meta/rRNA/bin_for_test/MAG2809_RMAG1998.e

the error file indicated no rRNA sequence were detected 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/89650706/160043561-760ccb9c-01f6-41af-a6ef-8af1231831fa.png">
and the output file is empty too.
Could any give me an interpretation? Many thanks in advance!
Best regards,
Jiangkun Yu

**Comment by dawnmy** [comment]
Hi Jiangkun Yu,

Thank you for your interest in RiboDetector. Our method is not designed for rRNA gene annotation for genomes. It is usually for identifying rRNA reads from sequencing data. To annotate rRNA gene in genome, you can try barrnap https://github.com/tseemann/barrnap. I hope this helps.

Best wishes,
Zhi-Luo

**Comment by ThomasYJK555** [comment]
Hi Zhi-Luo:
Thanks a lot for your interpretation, now I've got it and greatly
appreciate your recommendation for the method of rRNA gene annotation in
genomes.
Many thanks,
Jiangkun
