### ISSUE TITLE
Is it possible using Ribodector on metagenomic reads

### ISSUE THREAD

**Issue by lideyongJNU** [hzi-bifo/RiboDetector#19]
Thanks for this amazing tool. Can I use ribodetector to identify rRNA reads from metagenomic rather than transcriptomic data? Thereafter, I would like to assemble the extracted rRNA and explore the populations based on assembled rRNA sequences.

**Comment by dawnmy** [comment]
Yes, it can do exactly what you need. If you have paired end reads data, I recommend you set `-e` parameter to `norrna` which will identify all possible rRNA reads. And the `-r` output gives you the rRNA reads that you can do the assembly on.
