### ISSUE TITLE
About read length

### ISSUE THREAD

**Issue by gouwei1** [hzi-bifo/RiboDetector#20]
Hi,

The raw data's read length are from 100 to 250, but the mean length are 148. Which one should be added after -l.

Best,
Wei

**Comment by dawnmy** [comment]
I would suggest to use `-l 148`. It will be also fine to use `-l 100`. The final prediction will be nearly the same. With `-l 100`, the first 100bp will be used to determine whether the whole read is from rRNA. The output will be the whole read no matter which `-l` parameter is set.

**Comment by gouwei1** [comment]
I'll have a try. Thanks for your reply!
