### ISSUE TITLE
docker image for 0.2.6

### ISSUE THREAD

**Issue by NicoleGruenheit** [hzi-bifo/RiboDetector#22]
Hi,

I would like to use the newest version but the latest docker image is for version 0.2.2. Would it be possible to update the docker image?

Cheers,
Nicole

**Comment by dawnmy** [comment]
Hi Nicole,

I will build a docker image next week for latest version 0.2.7

Best,
Zhi-Luo

**Comment by dawnmy** [comment]
Hi Nicole,

I will build a docker image next week for latest version 0.2.7

Best,
Zhi-Luo

**Comment by dawnmy** [comment]
@NicoleGruenheit I have uploaded the CPU version (tag: 0.2.7-cpu). You should be able to pull it with:
```
docker pull dawnmy/ribodetector:0.2.7-cpu
```
Then you can run it with something like:
```
docker run -v <your local data dir>:<docker data dir> --rm dawnmy/ribodetector:0.2.7-cpu \
  ribodetector_cpu  -t 10 \
  -l 100 \
  -i <data dir/reads.1.fq.gz> <data dir/reads.2.fq.gz> \
  -e rrna \
  --chunk_size 512 \
  -o <data dir/reads.nonrrna.1.fq> <data dir/reads.nonrrna.2.fq>
```
We will upload the GPU version soon. But the GPU version image is very large. If you don't have GPU available on the computer, it would be better to install only the CPU version.

**Comment by dawnmy** [comment]
GPU version is also uploaded. 
```shell
docker pull dawnmy/ribodetector:0.2.7
```

Memory and  shared memory parameters need to be set with `docker run`, e.g.:
```
docker run --memory=<64>G --shm-size <32>G --gpus all \
  -v <your local data dir>:<docker data dir> --rm dawnmy/ribodetector:0.2.7-cpu \
  ribodetector_cpu  -t 10 \
  -l 100 \
  -i <data dir/reads.1.fq.gz> <data dir/reads.2.fq.gz> \
  -e rrna \
  --chunk_size 512 \
  -m 12
  -o <data dir/reads.nonrrna.1.fq> <data dir/reads.nonrrna.2.fq>
```
