### ISSUE TITLE
Recommendations on running RiboDetector twice on the fastq files?

### ISSUE THREAD

**Issue by resol341** [hzi-bifo/RiboDetector#30]
Hi,

First, thank you for such wonderful tool. It really help a lot with our data. I apologize this is a question rather than an actual issue.

We are working with this dataset where the ribo depletion essentially did not work (please see "before.html " in the attached zip file). After running RiboDetector, the "Per sequence GC content" was greatly improved (please see "after.html" in the attached zip file). The top Overrepresented sequences are blasted to be rRNA content still, albeit with reduced count. So my question is, would it be worthwhile/recommended to run RiboDetector for a second time on the fastq files? Would that further reduce the rRNA reads, or would it introduce some sort of bias? 

Our experiment was a simple bulk RNA-seq of mouse cells with low cell count/RNA as input. 
I ran RiboDetector with the following settings:

ribodetector \
          -t 10 \
          -l 150\
          -i ./${seq_name}_R1_001_val_1.fq.gz ./${seq_name}_R2_001_val_2.fq.gz \
          -m 40 \
          -e norrna \
          --chunk_size 256
          -o nonrrna/${seq_name}_R1_001.fastq.gz nonrrna/${seq_name}_R2_001.fastq.gz

Thank you again. 

Best!
[fastqc.zip](https://github.com/hzi-bifo/RiboDetector/files/10929092/fastqc.zip)

**Comment by dawnmy** [comment]
Thank you for your interest in RiboDetector (RD). Your command line looks good to me. Running RD for the second time will not further reduce the rRNA count in the output. How many remaining rRNA reads do you estimate in the output of RD? You could try a smaller -l parameter, e.g. 100.

**Comment by resol341** [comment]
Hi, Thank you for your reply. I have tried a few tools since submitting this question. It appears that using HTStream supplied with rRNA sequence .fa file completely removed all the rRNA contaminations. Since our data is single species (mouse), that was an easier solution for us. I understand RiboDetector might be oriented more for metatranscriptomic/metagenomic. Thank you for your time.
