### ISSUE TITLE
[ERROR] Unable to run ribodetector on a remote server:  No visible CUDA devices!

### ISSUE THREAD

**Issue by jwilliams648** [hzi-bifo/RiboDetector#36]
Hi I am currently trying to run ribodetector on my conda environment but keep on getting the following error: 

"ERROR  No visible CUDA devices! Please use detect_cpu.py to run it on CPU if you do not have GPU or 
you need to install GPU version of PyTorch"

I installed pytorch via conda, but the error still gets thrown. Any help in resolving this issue would be appreciated.

**Comment by dawnmy** [comment]
You can try to check whether you have CUDA device to use with: `echo $CUDA_VISIBLE_DEVICES`. If this returns nothing, you might not have any CUDA device available for you to use on this machine. Then you should go for the CPU mode of RiboDetector with `ribodetector_cpu` command
