### ISSUE TITLE
Retrive the filtered out sequences

### ISSUE THREAD

**Issue by LeoVincenzi** [hzi-bifo/RiboDetector#38]
Hi dear developers,
thanks for this interesting tools!
I have a question about the possibility it give us: the output file is the fastq of the remaining sequences after rrna reads have been removed. I would like to know if there is the possibility to have in output the sequences that have been filtered out by the process. If there is, it would be fantastic.

Thanks!
Leo

**Comment by dawnmy** [comment]
Glad that you found RiboDetector is useful for you. Yes, you can use `-r` parameter where you can specify the path for the output sequence file of detected rRNAs.

**Comment by LeoVincenzi** [comment]
Oh sorry, I completely missed that line in the guide. 
Thank you very much!!
