### ISSUE TITLE
Can we apply this tool for custom reference sequences?

### ISSUE THREAD

**Issue by ssun1116** [hzi-bifo/RiboDetector#43]
Firstly, I want to express my gratitude for your fantastic tool!

Using your tool, I want to expand my analysis further by incorporating custom reference sequences, specifically tRNA sequences from GtRNAdb. Is there a way to integrate custom reference sequences into running your code?

Thank you in advance!
Seoyeon Kim

**Comment by dawnmy** [comment]
Thank you for using RiboDetector. As of now, our software does not have the capability to identify tRNA sequences. This would require training a specific model for tRNA, which is not currently in our development plans. But you can map the reads against tRNA references using short reads aligners with strict cutoffs.

**Comment by ssun1116** [comment]
Thanks for your clarification! :)
