### ISSUE TITLE
Classification of the rRNA removed seqeunces

### ISSUE THREAD

**Issue by LeoVincenzi** [hzi-bifo/RiboDetector#45]
Dear developers, 
I have a question about the reads discarded by Ribodetector: can the software report which kind of rRNA sequences they contain (mammalian, bacteria, etc..)? Or which database would you suggest using to identify this information in the removed reads?
Thanks for your help,
Leonardo

**Comment by dawnmy** [comment]
You could map the output rRNA reads against SILVA database: 
[SILVA_138.1_LSURef_NR99_tax_silva.fasta.gz](https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_138.1_LSURef_NR99_tax_silva.fasta.gz) and [SILVA_138.1_SSURef_NR99_tax_silva.fasta.gz](https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_138.1_SSURef_NR99_tax_silva.fasta.gz) using short reads aligner. Then you should be able to get the taxonomy information of the reads.

**Comment by LeoVincenzi** [comment]
Okay, thank you very much. By your experience, would you suggest using BWA or bowtie2?

**Comment by dawnmy** [comment]
I think they are similar, BWA has BWA-mem2 which might be good to try
