### ISSUE TITLE
RiboDetector for barcoded libraries

### ISSUE THREAD

**Issue by mckellardw** [hzi-bifo/RiboDetector#51]
I am working with spatial transcriptomics data (10x Genomics Visium, etc), where read 1 contains only barcode information and read 2 has the actual sequence. Could you add a flag to disable predictions on R1, but still filter the fastq based on the label predicted for R2?

**Comment by dawnmy** [comment]
Hi, we will consider adding this option in a future release but I am not sure when. For now, you can use the approach outlined here: https://github.com/hzi-bifo/RiboDetector/issues/41 to achieve this.

**Comment by mckellardw** [comment]
Thanks!
