### ISSUE TITLE
unexpected large proportion of rRNA reads detected by RiboDetector

### ISSUE THREAD

**Issue by Ivy-ops** [hzi-bifo/RiboDetector#53]
Hi developer, 
Thank you for creating such a fast and helpful software; it's been very useful for my work.

My objective is to remove rRNA reads and retain only those reads that do not contain rRNA. The average length of my reads is 141.  When I used the code below, it successfully generated 2 fq files. However, I noticed that over 90% of the reads were removed after running RiboDetector. This result is unexpected, since I had already depleted the rRNA during the experiment. Could you please provide some suggestions or guidance on this?

Thank you!

```
MEAN_READ_LENGTH=`zcat ${sample_name}_R1.fastq.gz | head -1000 | awk '{if(NR%4==2) {count++; bases += length} } END {print int(bases/count)}' || true`
ribodetector_cpu -t 20 \
                 -l ${MEAN_READ_LENGTH} \
                 -i ${sample_name}_R1.fastq.gz ${sample_name}_R2.fastq.gz \
                 -e norrna \
                 --chunk_size 1000 \
                 -o ${sample_name}_no_rRNA_R1.fq ${sample_name}_no_rRNA_R2.fq
```

**Comment by dawnmy** [comment]
Could you try using `-e rrna` to ensures only rRNAs with high confidence are remove ? The percentage of detected rRNA reads should drop. And also, it is not unusual for an experimentally rRNA-depleted sample to still contain a large proportion of rRNAs.

**Comment by Ivy-ops** [comment]
Hi @dawnmy , 
Thanks for the quick response! 
Just to confirm, does `-e rrna ` retain the non-rRNA reads, while `-e norrna` retains the rRNA reads? 
Does that mean: my previous code is retaining the rRNA reads? 
Appreciated!

**Comment by dawnmy** [comment]
The `-e rrna` option will classify only high-confidence predicted rRNA as rRNA, whereas `-e norrna` will also classify medium-confidence predicted rRNA as rRNA. If the `-o` and `-r` parameters are set, both non-rRNA and rRNA output files will be generated regardless of the `-e` setting.

Here is the explanation from the help message:
```
-e {rrna,norrna,both,none}, --ensure {rrna,norrna,both,none}
                        Ensure which classificaion has high confidence for paired end reads.
                        norrna: output only high confident non-rRNAs, the rest are clasified as rRNAs;
                        rrna: vice versa, only high confident rRNAs are classified as rRNA and the rest output as non-rRNAs;
                        both: both non-rRNA and rRNA prediction with high confidence;
                        none: give label based on the mean probability of read pair.
```

**Comment by Ivy-ops** [comment]
Nice, Thanks for the quick clarification, @dawnmy ! I will try and see!

**Comment by Ivy-ops** [comment]
Hi @dawnmy , 
I tested my datasets with below code based on your suggestions: 
```
MEAN_READ_LENGTH=`zcat ${qc_dir}/${sample_name}_R1.bbduk.fastq.gz | head -1000 | awk '{if(NR%4==2) {count++; bases += length} } END {print int(bases/count)}' || true`
ribodetector_cpu -t 20 \
                 -l ${MEAN_READ_LENGTH} \
                 -i ${qc_dir}/${sample_name}_R1.bbduk.fastq.gz ${qc_dir}/${sample_name}_R2.bbduk.fastq.gz \
                 -e none \
                 --chunk_size 1000 \
                 -o ${ribodetector_dir}/${sample_name}_norRNA_R1.fq ${ribodetector_dir}/${sample_name}_norRNA_R2.fq \
                 -r ${ribodetector_dir}/${sample_name}_rRNA_R1.fq ${ribodetector_dir}/${sample_name}_rRNA_R2.fq
```
As a result, ~ 90% of reads are retained in ${ribodetector_dir}/${sample_name}_RNA_R1.fq and ${ribodetector_dir}/${sample_name}_RNA_R2.fq. However, when I used these norRNA fastq files to align to the mouse genome with STAR and analyzed them with htseq-count, I still discovered a substantial number of rRNA genes, mt-Rnr1 and mt-Rnr2. 

For example, in one sample, out of the original 25,721,937 read pairs, only 4,050,551 pairs were classified as norRNA reads, while 21,671,386 pairs were identified as rRNA reads. The STAR alignment and htseq-count reported a total of 418,373 gene counts, with 102,559 attributed to mt-Rnr1 and 163,698 to mt-Rnr2.

Your suggestions are highly appreciated!

**Comment by dawnmy** [comment]
Do you mean with `-e none` you still have >90% reads classified as rRNA (21,671,386)? In the identified non-rRNA reads (4,050,551 ) you have 102,559 + 163,698 reads can be actually mapped to mt-Rnr genes?

**Comment by Ivy-ops** [comment]
Hi @dawnmy , 
Yes, you are correct! I am afraid anything wrong on my code? 
I’d really appreciate your input!

**Comment by dawnmy** [comment]
the way you run RiboDetector looks fine. You data might have very large fraction of rRNA reads. Are your data mice RNAseq data? or metatranscriptome data? Could you check the number of mapped reads in the SAM/BAM file with `samtools flagstats <your BAM file>` because htseq-count may exclude multiple alignments?

**Comment by Ivy-ops** [comment]
Hi @dawnmy , 
Thanks for the suggestion. 
My data is mice transcriptomic data. 
I ran `samtools flagstats` and received the following output:
```
1876833 + 0 in total (QC-passed reads + QC-failed reads)
1440764 + 0 primary
436069 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
1876833 + 0 mapped (100.00% : N/A)
1440764 + 0 primary mapped (100.00% : N/A)
1440764 + 0 paired in sequencing
720420 + 0 read1
720344 + 0 read2
1440582 + 0 properly paired (99.99% : N/A)
1440582 + 0 with itself and mate mapped
182 + 0 singletons (0.01% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

After that, I used htseq-count to count all genes (including paired and unpaired) with below code: 
`htseq-count -f bam -r pos -s no -t exon -i gene_id --nonunique all \
    ${aligned_bam} ${gtf_file} > ${htseq_dir}/${sample_name}_counts_all.txt`

As a result, the total number of detected genes slightly increased to 429,590. However, 102,585 mt-Rnr1 and 163,746 mt-Rnr2 genes were still found. Could you clarify why ribodetector is unable to filter out these two rRNA genes? Is this caused by the database? 
Thank you so much!

**Comment by dawnmy** [comment]
The two mitochondrial rRNA genes might not be fully represented in RiboDetector's training data. Another reason could be that your alignment with STAR may map some non-rRNA reads to mt-Rnr1 and mt-Rnr2 due to partial alignment, where only a small region of the reads maps to the genes. You can verify this by checking the alignment.

Based on the numbers you provided, RiboDetector missed 102,585 + 163,746 rRNA reads but detected 21,671,386 rRNA reads. Assuming these 21,671,386 are all true positives and 102,585 + 163,746 are false negatives, the sensitivity/recall would be approximately 99%, which matches the performance I demonstrated in the benchmarks.

If you want to eliminate as many potential rRNA reads as possible, you can try the `-e norrna` option, which you mentioned in your first post. You can then check how many mt-Rnr reads remain in your initial run where you used `-e norrna`.

**Comment by Ivy-ops** [comment]
Hi @dawnmy , 
Thank you for your input! I tried using the -e norrna option, but the two mitochondrial rRNA genes are still being included in the counts.
Is there a way to specifically exclude the mitochondrial rRNA genes in RiboDetector?
Thank you!

**Comment by dawnmy** [comment]
If the `-e norrna` option in RiboDetector fails to detect certain rRNA genes, you can add an additional filtering step. Use bwa2 with a longer seed length (e.g., 51) to map the non-rRNA output from RiboDetector to the mt-Rnr genes. Retain the unmapped sequences as non-rRNA for downstream gene counting.

**Comment by Ivy-ops** [comment]
Thank you! @dawnmy
