### ISSUE TITLE
Lost reads?

### ISSUE THREAD

**Issue by sjaenick** [hzi-bifo/RiboDetector#7]
I ran ribodetector on a public dataset (SRR3569371) which contains 44.9 mio read pairs (44.921.923).

`-e rrna`: Output contains 13.515.399 read pairs
`-e norrna`: Output contains 9.155.513 read pairs

13.515.399 + 9.155.513 = 22.670.912 - so approx. half of all input reads are lost?

**Comment by dawnmy** [comment]
I think you misunderstand the `-e` option. 
For example , `-e rrna` is to tell the classifier to output only high confident rRNA reads in the rRNA output (file specified with `-r`) and the rest of the reads go to the non-rRNA output (file specified with `-o`).

And `-e norrna` means the opposite, i.e. ensure the nonrRNA (`-o`) output are only confident nonrRNA reads.

So, to check the total output reads you need to sum up the reads in `-r` and `-o` outputs. The sum should be the same with the input reads for `rrna`, `norrna` and `none`, but not for `both`. For `both`, only high confident rRNA and non-rRNA reads are kept in `-r` and `-o` output.

**Comment by sjaenick** [comment]
Ok, thanks for the clarification.
